language: node_js
node_js:
  - 15
branches:
  only:
    - main
services:
  - mongodb
before_install:
  - openssl aes-256-cbc -K $encrypted_83cbab1bbca1_key -iv $encrypted_83cbab1bbca1_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
install: npm install --save-dev
script:
  - npm test
  - npm run lint:node
  - npm run lint:browser
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/id_rsa
  - ssh-add .travis/id_rsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - cd ~
  - git clone https://github.com/wsi-2021/chicagovaxtracker.com.git chicagovaxtracker.com
  - cd chicagovaxtracker.com
  - git remote add live $DEPLOY_URL
  - git push live main
