#! /usr/bin/env sh
# Hold onto the root of the repository
REPO_ROOT=$(git rev-parse --show-toplevel)
PRE_COMMIT_HOOK=$REPO_ROOT/.git/hooks/pre-commit

# Check to see if the pre-commit symlink exists. If not, create it.
if [ ! -L "$PRE_COMMIT_HOOK" ]; then
  # Link the pre-commit hook relative to the `.git/hooks` directory
  # This assumes that you're storing your hooks at $REPO_ROOT/scripts/hooks.
  # Adjust the path as necessary.
  ln -s ../../scripts/hooks/pre-commit $PRE_COMMIT_HOOK
fi

# Install all dependencies, including development dependencies
npm install --save-dev
